In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/Users/aftaabmulla/Neural-Networks/DataSet/dog-breed-identification/labels.csv")

In [3]:
data.head()

                                 id             breed
0  000bec180eb18c7604dcecc8fe0dba07       boston_bull
1  001513dfcb2ffafc82cccf4d8bbaba97             dingo
2  001cdf01b096e06d78e9e5112d419397          pekinese
3  00214f311d5d2247d5dfe4fe24b2303d          bluetick
4  0021f9ceb3235effd7fcde7f7538ed62  golden_retriever

In [4]:
data.tail()

                                     id                     breed
10217  ffd25009d635cfd16e793503ac5edef0                    borzoi
10218  ffd3f636f7f379c51ba3648a9ff8254f            dandie_dinmont
10219  ffe2ca6c940cddfee68fa3cc6c63213f                  airedale
10220  ffe5f6d8e2bff356e9482a80a6e29aac        miniature_pinscher
10221  fff43b07992508bc822f33d8ffd902ae  chesapeake_bay_retriever

# Getting our WorkSpace Ready

In [3]:
import tensorflow as tf

In [4]:
print(f"TensorFlow Version : {tf.__version__}")

TensorFlow Version : 2.16.2